############### WORKDIR ################
#### path to store results ####
## Note that following paths are internal to docker container, and can not be edited
## To map respective host volume, docker run with -v <path in host scratch>:/mnt/scratch -v <path in host evocore>:/mnt/evocore arg
## workdir is given at the run command to provide sample-specific workdir
# workdir: "/mnt/scratch/snakemake/sjc_titan/tumor1"
## snakemake dir: snakemake must run from this dir
smk_home: "/mnt/evocore/repos/TitanCNA/scripts/snakemake"
## tmp dir
tempdir: "/mnt/scratch/tmp"

## path to tools
samTools:  /opt/miniconda/bin/samtools

## path to scripts ##
readCounterScript:  /mnt/evocore/configs/bin/readCounter
ichorCNA_rscript:  /mnt/evocore/repos/ichorCNA/scripts/runIchorCNA.R
ichorCNA_libdir:  /mnt/evocore/repos/ichorCNA/
pyCountScript:  /mnt/evocore/repos/TitanCNA/scripts/snakemake/code/countPysam.py
TitanCNA_rscript: /mnt/evocore/repos/TitanCNA/scripts/R_scripts/titanCNA.R
TitanCNA_selectSolutionRscript: /mnt/evocore/repos/TitanCNA/scripts/R_scripts/selectSolution.R
TitanCNA_libdir:  /mnt/evocore/repos/TitanCNA/

## reference settings and paths to reference files ##
genomeBuild: hg38
genomeStyle:  UCSC
refFasta:  /mnt/scratch/refdata/Homo_sapiens_assembly38.fasta
snpVCF:  /mnt/scratch/refdata/hapmap_3.3.hg38.vcf.gz
ichorCNA_exons: NULL
cytobandFile:  /mnt/scratch/refdata/cytoBandIdeo.txt
centromere:  /mnt/evocore/repos/ichorCNA/inst/extdata/GRCh38.GCA_000001405.2_centromere_acen.txt
sex:  None   # use None if both females and males are in sample set

## standard parameters for qsub memory, runtime, pe (parallel environment)
# use what your scheduler designates for parameters; does not apply to local run
# invoke using:
# snakemake -s TitanCNA.snakefile --cluster-sync "qsub -l h_vmem={params.mem},h_rt={params.runtime} {params.pe}" -j 100 --jobscript config/cluster.sh
std_mem:  4G
std_runtime:  "05:00:00"  
std_numCores:  -pe smp 1 -binding linear:1

## params for each step ##

## read depth params ##
# use this for NCBI chr naming
# chrs: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y 
# use this for UCSC chr naming
chrs: chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY 
binSize:  10000

## ichorCNA params ##
ichorCNA_gcWig: /mnt/evocore/repos/ichorCNA/inst/extdata/gc_hg38_10kb.wig
ichorCNA_mapWig:  /mnt/evocore/repos/ichorCNA/inst/extdata/map_hg38_10kb.wig
ichorCNA_chrs:  c(1:22, \"X\")
ichorCNA_normal:  c(0.5)  
ichorCNA_ploidy:  c(2,3)  
ichorCNA_estimateNormal:  TRUE
ichorCNA_estimatePloidy:  TRUE
ichorCNA_estimateClonality: TRUE
ichorCNA_scStates:  c(1,3)
## maxCN has no impact on segments with CN > 4
## https://github.com/gavinha/TitanCNA/issues/28
ichorCNA_maxCN:  8
ichorCNA_includeHOMD: FALSE
ichorCNA_txnE:  0.9999
ichorCNA_txnStrength:  10000
ichorCNA_plotFileType:  png
ichorCNA_plotYlim:  c(-2,4)
ichorCNA_mem:  10G
ichorCNA_runtime:  "300:00:00"
ichorCNA_pe: -pe smp 1 -binding linear:1  

## allele counts - samtools, pysam ##
# USERS MUST MODIFY getAlleleCounts.snakefile to use the correct CHRS naming
map_quality:  10
base_quality: 10
vcf_quality:  100

## TitanCNA params ##
TitanCNA_maxNumClonalClusters: 2
TitanCNA_chrs:  c(1:22, \"X\")
TitanCNA_normalInit: 0.5
TitanCNA_maxPloidy: 3
TitanCNA_estimateNormal:  map
TitanCNA_estimatePloidy:  TRUE
TitanCNA_estimateClonality: TRUE
TitanCNA_alleleModel: binomial
TitanCNA_alphaK:  10000
TitanCNA_alphaR:  10000
TitanCNA_txnExpLen: 1e15
TitanCNA_plotYlim:  c(-2,4)
TitanCNA_solutionThreshold: 0.05
TitanCNA_numCores: 1
TitanCNA_mem:  16G
TitanCNA_runtime:  "300:00:00"
TitanCNA_pe: -pe smp 1 -binding linear:1  
